refactor: change Windows runner to the latest
The reason why we have been using `-2022` instead of `-latest` is that we got a following error,
> Error: Tried to map a target OS from env. variable 'ImageOS' (got win25), but failed.
> If you're using a self-hosted runner, you should set 'env': 'ImageOS': ...
> to one of the following: ['ubuntu22', 'ubuntu24', 'win19', 'win22', 'macos13', 'macos14', 'macos15']

Since then, it has already improved, erlef/setup-beam now supports `windows-2025` as well.
https://github.com/erlef/setup-beam/pull/388